# custom join statement defined in setup.__init__ 

# <> must be replaced with user generated values.

modes: #: external programs used to parse data
  <mode>: #: [List of relevant columns generated for mode in database]
irida:
  project_number: #: Project id assigned by irida
  project_name: #: Project name assigned by irida
  username: #: Username for irida permissions
  password: #: Password for irida permissions
  storage: #: Location to store irida shortcuts (only used if not overridden in command line options)
kraken2:
  db_path: #: location of kraken2 database on server
folder:
  # custom join statement defined in setup.__init__ 
  output: #: Where xlsx and html output files from reports will be stored.
  old_db_path: #: Location of old database export file for retrieving dates. Not necessary if date in sample name.
control_types: #: Archetypes of control samples
  <controltype>: #: Control archetype name. 
    targets: #: [List of target genera for control type]
    regex: #: Regular expression used to parse this control type
date_regex: #: Regular expression used to parse submission date.
rerun_regex: #: Regular expression used to parse whether a sample is a rerun