"""added in unchanging reads to contains and adding matches

Revision ID: 50e3759aad35
Revises: a5bcaf6fc037
Create Date: 2022-11-02 10:31:26.336513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '50e3759aad35'
down_revision = 'a5bcaf6fc037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contains', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('matches', sa.JSON(), nullable=True))
        batch_op.drop_column('reads')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reads', sqlite.JSON(), nullable=True))
        batch_op.drop_column('matches')
        batch_op.drop_column('contains')

    # ### end Alembic commands ###
