"""added in unique names

Revision ID: a5bcaf6fc037
Revises: fc734f32a71b
Create Date: 2022-10-31 10:59:33.723988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bcaf6fc037'
down_revision = 'fc734f32a71b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_control_name', ['name'])

    with op.batch_alter_table('_control_types', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_control_type_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_control_type_name', type_='unique')

    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.drop_constraint('uq_control_name', type_='unique')

    # ### end Alembic commands ###
