"""Add in kraken data

Revision ID: a63e4c8a10e0
Revises: 50e3759aad35
Create Date: 2022-11-23 13:17:26.464778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63e4c8a10e0'
down_revision = '50e3759aad35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kraken', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.drop_column('kraken')

    # ### end Alembic commands ###
