"""Adding in reads for controls

Revision ID: e595da3bdbce
Revises: 04703b340c95
Create Date: 2022-10-26 11:30:47.477584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e595da3bdbce'
down_revision = '04703b340c95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reads', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_control_samples', schema=None) as batch_op:
        batch_op.drop_column('reads')

    # ### end Alembic commands ###
