"""Changed names of back_pops

Revision ID: fc734f32a71b
Revises: e595da3bdbce
Create Date: 2022-10-26 13:32:36.553833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc734f32a71b'
down_revision = 'e595da3bdbce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
